### ISSUE TITLE
Deleting too many assets

### ISSUE THREAD

**Issue by Pat-a-wan** [PlasmaEngine/PlasmaEngine#68] opened 2021-03-09 00:29 UTC
Deleting too many assets makes the confirmation screen larger than it should be, making it so we cannot select yes or ok. 

also didn't allow usage of enter, esc, etc

**Comment by DaveTheGameDev** [comment] 2021-03-19 08:28
closing due to duplicate of #48

**Closed by DaveTheGameDev** 2021-03-19 08:28 UTC
